# Generated by Django 5.2.16 on 2026-07-23 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_initial_grave_site_lookups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraveSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Veřejné"),
                            ("authenticated", "Pouze přihlášení"),
                            ("restricted", "Omezené"),
                            ("admin_only", "Pouze správce"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Ověřeno"),
                            ("probable", "Pravděpodobné"),
                            ("uncertain", "Nejisté"),
                            ("disputed", "Sporné"),
                            ("unconfirmed", "Nepotvrzené"),
                        ],
                        default="unconfirmed",
                        max_length=20,
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("archive_reason", models.TextField(blank=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("deletion_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("existing", "Existující"),
                            ("destroyed", "Zaniklé"),
                            ("unknown", "Existence neznámá"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "location_text",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "cemetery_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "section",
                    models.CharField(blank=True, max_length=100),
                ),
                ("row", models.CharField(blank=True, max_length=100)),
                (
                    "grave_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("inscription", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grave_site_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grave_sites",
                        to="places.gravesitetype",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grave_sites",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hrobové nebo pamětní místo",
                "verbose_name_plural": "Hrobová a pamětní místa",
                "ordering": (
                    "cemetery_name",
                    "section",
                    "row",
                    "grave_number",
                    "pk",
                ),
            },
        ),
    ]
