# Generated by Django 5.2.16 on 2026-07-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0009_alter_person_options"),
        ("places", "0008_gravesite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonGraveSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Veřejné"),
                            ("authenticated", "Pouze přihlášení"),
                            ("restricted", "Omezené"),
                            ("admin_only", "Pouze správce"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Ověřeno"),
                            ("probable", "Pravděpodobné"),
                            ("uncertain", "Nejisté"),
                            ("disputed", "Sporné"),
                            ("unconfirmed", "Nepotvrzené"),
                        ],
                        default="unconfirmed",
                        max_length=20,
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("archive_reason", models.TextField(blank=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("deletion_reason", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grave_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_links",
                        to="places.gravesite",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grave_site_links",
                        to="people.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_grave_site_links",
                        to="places.persongravesiterole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propojení osoby s hrobovým místem",
                "verbose_name_plural": (
                    "Propojení osob s hrobovými místy"
                ),
                "ordering": (
                    "person_id",
                    "grave_site_id",
                    "role__sort_order",
                    "role__name",
                    "pk",
                ),
            },
        ),
    ]
