# Generated by Django 5.2.16 on 2026-07-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, editable=False)),
                ('supports_date_range', models.BooleanField(default=False)),
                ('allows_place', models.BooleanField(default=True)),
                ('default_show_in_overview', models.BooleanField(default=False)),
                ('default_access_level', models.CharField(choices=[('public', 'Veřejné'), ('authenticated', 'Pouze přihlášení'), ('restricted', 'Omezené'), ('admin_only', 'Pouze správce')], default='public', max_length=20)),
            ],
            options={
                'verbose_name': 'Typ události',
                'verbose_name_plural': 'Typy událostí',
                'ordering': ('sort_order', 'name', 'code'),
                'abstract': False,
            },
        ),
    ]
