# Generated by Django 5.2.16 on 2026-07-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial_event_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Role účastníka',
                'verbose_name_plural': 'Role účastníků',
                'ordering': ('sort_order', 'name', 'code'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllowedEventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveSmallIntegerField(default=0)),
                ('max_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, editable=False)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowed_roles', to='events.eventtype')),
                ('participant_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_type_rules', to='events.participantrole')),
            ],
            options={
                'verbose_name': 'Povolená role události',
                'verbose_name_plural': 'Povolené role událostí',
                'ordering': ('event_type__sort_order', 'sort_order', 'participant_role__sort_order', 'participant_role__code'),
                'constraints': [models.UniqueConstraint(fields=('event_type', 'participant_role'), name='events_unique_allowed_role'), models.CheckConstraint(condition=models.Q(('max_count__isnull', True), ('max_count__gte', models.F('min_count')), _connector='OR'), name='events_valid_allowed_role_counts')],
            },
        ),
    ]
