# Generated by Django 5.2.16 on 2026-07-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event'),
        ('people', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to='people.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to='events.participantrole')),
            ],
            options={
                'verbose_name': 'Účastník události',
                'verbose_name_plural': 'Účastníci událostí',
                'ordering': ('role__sort_order', 'person__last_name', 'person__first_name', 'person_id'),
                'constraints': [models.UniqueConstraint(fields=('event', 'person', 'role'), name='events_unique_participation')],
            },
        ),
    ]
