# Generated by Django 5.2.16 on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeathDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cause", models.TextField(blank=True)),
                ("circumstances", models.TextField(blank=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="death_detail",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detail úmrtí",
                "verbose_name_plural": "Detaily úmrtí",
            },
        ),
    ]
