# Generated by Django 5.2.16 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttachmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(default=False, editable=False),
                ),
            ],
            options={
                "verbose_name": "Kategorie přílohy",
                "verbose_name_plural": "Kategorie příloh",
                "ordering": ("sort_order", "name", "code"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttachmentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(default=False, editable=False),
                ),
            ],
            options={
                "verbose_name": "Role přílohy",
                "verbose_name_plural": "Role příloh",
                "ordering": ("sort_order", "name", "code"),
                "abstract": False,
            },
        ),
    ]
