# Generated by Django 5.2.16 on 2026-08-30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_attachment_lookups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("exact", "Přesné datum"),
                            ("month", "Měsíc a rok"),
                            ("year", "Pouze rok"),
                            ("range", "Rozmezí"),
                            ("unknown", "Neznámé datum"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "date_qualifier",
                    models.CharField(
                        choices=[
                            ("none", "Bez kvalifikátoru"),
                            ("approximate", "Přibližně"),
                            ("before", "Před"),
                            ("after", "Po"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("start_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("start_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("start_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("original_date_text", models.CharField(blank=True, max_length=255)),
                ("date_note", models.TextField(blank=True)),
                ("sort_date", models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ("sort_date_end", models.DateField(blank=True, editable=False, null=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Veřejné"),
                            ("authenticated", "Pouze přihlášení"),
                            ("restricted", "Omezené"),
                            ("admin_only", "Pouze správce"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("archive_reason", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("deletion_reason", models.TextField(blank=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("mime_type", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "sha256",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_sha256",
                                message=(
                                    "Kontrolní součet musí být SHA-256 zapsaný "
                                    "64 malými hexadecimálními znaky."
                                ),
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "file_status",
                    models.CharField(
                        choices=[
                            ("pending", "Čeká na potvrzení"),
                            ("available", "Dostupný"),
                            ("missing", "Nedostupný"),
                            ("quarantined", "V karanténě"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("creator_name", models.CharField(blank=True, max_length=255)),
                ("provenance", models.TextField(blank=True)),
                ("original_owner", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=35)),
                ("technical_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="materials.attachmentcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Příloha",
                "verbose_name_plural": "Přílohy",
            },
        ),
    ]
