# Generated by Django 5.2.16 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_attachment_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(default=False, editable=False),
                ),
            ],
            options={
                "verbose_name": "Typ zdroje",
                "verbose_name_plural": "Typy zdrojů",
                "ordering": ("sort_order", "name", "code"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(default=False, editable=False),
                ),
            ],
            options={
                "verbose_name": "Role zdroje",
                "verbose_name_plural": "Role zdrojů",
                "ordering": ("sort_order", "name", "code"),
                "abstract": False,
            },
        ),
    ]
