# Generated by Django 5.2.16 on 2026-09-02 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_source_lookups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_level', models.CharField(choices=[('public', 'Veřejné'), ('authenticated', 'Pouze přihlášení'), ('restricted', 'Omezené'), ('admin_only', 'Pouze správce')], default='public', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('date_precision', models.CharField(choices=[('exact', 'Přesné datum'), ('month', 'Měsíc a rok'), ('year', 'Pouze rok'), ('range', 'Rozmezí'), ('unknown', 'Neznámé datum')], default='unknown', max_length=10)),
                ('date_qualifier', models.CharField(choices=[('none', 'Bez kvalifikátoru'), ('approximate', 'Přibližně'), ('before', 'Před'), ('after', 'Po')], default='none', max_length=12)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_date_text', models.CharField(blank=True, max_length=255)),
                ('date_note', models.TextField(blank=True)),
                ('sort_date', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('sort_date_end', models.DateField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('full_citation', models.TextField(blank=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('fonds', models.CharField(blank=True, max_length=255)),
                ('shelfmark', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=100)),
                ('inventory_number', models.CharField(blank=True, max_length=100)),
                ('creator_name', models.CharField(blank=True, max_length=255)),
                ('publication_details', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('accessed_on', models.DateField(blank=True, null=True)),
                ('external_identifier', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='materials.sourcetype')),
            ],
            options={
                'verbose_name': 'Zdroj',
                'verbose_name_plural': 'Zdroje',
                'ordering': ('title', 'pk'),
            },
        ),
    ]
