# Generated by Django 5.2.16 on 2026-09-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_health_records'),
        ('materials', '0006_source_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_level', models.CharField(choices=[('public', 'Veřejné'), ('authenticated', 'Pouze přihlášení'), ('restricted', 'Omezené'), ('admin_only', 'Pouze správce')], default='public', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('context_description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_record_links', to='materials.attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_links', to='health.healthrecord')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_links', to='materials.attachmentrole')),
            ],
            options={
                'verbose_name': 'Příloha zdravotního záznamu',
                'verbose_name_plural': 'Přílohy zdravotních záznamů',
                'ordering': ('health_record_id', 'sort_order', 'role__sort_order', 'pk'),
            },
        ),
    ]
