# Generated by Django 5.2.16 on 2026-09-04 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_health_records'),
        ('materials', '0007_health_record_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecordSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_level', models.CharField(choices=[('public', 'Veřejné'), ('authenticated', 'Pouze přihlášení'), ('restricted', 'Omezené'), ('admin_only', 'Pouze správce')], default='public', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('cited_part', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('interpretation', models.TextField(blank=True)),
                ('support_strength', models.CharField(choices=[('confirms', 'Potvrzuje'), ('suggests', 'Naznačuje'), ('supplements', 'Doplňuje'), ('contradicts', 'Odporuje')], max_length=20)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='health.healthrecord')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_links', to='materials.sourcerole')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_links', to='materials.source')),
            ],
            options={
                'verbose_name': 'Zdroj zdravotního záznamu',
                'verbose_name_plural': 'Zdroje zdravotních záznamů',
                'ordering': ('health_record_id', 'role__sort_order', 'pk'),
            },
        ),
    ]
