# Generated by Django 5.2.16 on 2026-07-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'permissions': (
                    (
                        'view_restricted_content',
                        'Může zobrazit omezený obsah',
                    ),
                    (
                        'view_admin_only_content',
                        'Může zobrazit obsah pouze pro správce',
                    ),
                ),
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
