# Generated by Django 5.2.16 on 2026-07-16 09:30

from django.db import migrations


INITIAL_PERSON_CATEGORIES = (
    {
        "code": "direct_family",
        "name": "Přímá rodina",
        "description": "Přímí předci a potomci.",
        "sort_order": 10,
    },
    {
        "code": "other_family",
        "name": "Ostatní rodina",
        "description": (
            "Vzdálenější příbuzenstvo a osoby příbuzné sňatkem."
        ),
        "sort_order": 20,
    },
    {
        "code": "close_to_family",
        "name": "Blízcí rodině",
        "description": (
            "Rodinní přátelé, kmotři a další dlouhodobě blízké osoby."
        ),
        "sort_order": 30,
    },
    {
        "code": "clergy",
        "name": "Duchovní",
        "description": (
            "Duchovní významně spojení s rodinou nebo jejím příběhem."
        ),
        "sort_order": 40,
    },
    {
        "code": "other_related",
        "name": "Další související osoby",
        "description": "Další osoby důležité pro rodinný příběh.",
        "sort_order": 50,
    },
)
INITIAL_PERSON_CATEGORY_CODES = tuple(
    category["code"] for category in INITIAL_PERSON_CATEGORIES
)


def create_initial_person_categories(apps, schema_editor) -> None:
    person_category = apps.get_model("people", "PersonCategory")

    for category in INITIAL_PERSON_CATEGORIES:
        person_category.objects.update_or_create(
            code=category["code"],
            defaults={
                "name": category["name"],
                "description": category["description"],
                "sort_order": category["sort_order"],
                "is_active": True,
                "is_system": True,
            },
        )


def remove_initial_person_categories(apps, schema_editor) -> None:
    person_category = apps.get_model("people", "PersonCategory")
    person_category.objects.filter(
        code__in=INITIAL_PERSON_CATEGORY_CODES
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_person_category'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_person_categories,
            remove_initial_person_categories,
        ),
    ]
