# Generated by Django 5.2.16 on 2026-07-16 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Typ jména',
                'verbose_name_plural': 'Typy jmen',
                'ordering': ('sort_order', 'name', 'code'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_level', models.CharField(choices=[('public', 'Veřejné'), ('authenticated', 'Pouze přihlášení'), ('restricted', 'Omezené'), ('admin_only', 'Pouze správce')], default='public', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Ověřeno'), ('probable', 'Pravděpodobné'), ('uncertain', 'Nejisté'), ('disputed', 'Sporné'), ('unconfirmed', 'Nepotvrzené')], default='unconfirmed', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('date_precision', models.CharField(choices=[('exact', 'Přesné datum'), ('month', 'Měsíc a rok'), ('year', 'Pouze rok'), ('range', 'Rozmezí'), ('unknown', 'Neznámé datum')], default='unknown', max_length=10)),
                ('date_qualifier', models.CharField(choices=[('none', 'Bez kvalifikátoru'), ('approximate', 'Přibližně'), ('before', 'Před'), ('after', 'Po')], default='none', max_length=12)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_date_text', models.CharField(blank=True, max_length=255)),
                ('date_note', models.TextField(blank=True)),
                ('sort_date', models.DateField(blank=True, db_index=True, editable=False, null=True)),
                ('sort_date_end', models.DateField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('name_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_names', to='people.nametype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='people.person')),
            ],
            options={
                'verbose_name': 'Jméno osoby',
                'verbose_name_plural': 'Jména osob',
                'ordering': ('name_type__sort_order', 'value'),
            },
        ),
    ]
