# Generated by Django 5.2.16 on 2026-07-16 09:54

from django.db import migrations


INITIAL_NAME_TYPES = (
    {
        "code": "birth_name",
        "name": "Rodné jméno",
        "description": "Jméno nebo příjmení používané při narození.",
        "sort_order": 10,
    },
    {
        "code": "additional_given_name",
        "name": "Další křestní jméno",
        "description": "Další křestní nebo osobní jméno.",
        "sort_order": 20,
    },
    {
        "code": "alternative_name",
        "name": "Alternativní zápis",
        "description": "Jiný historický nebo dokumentovaný zápis jména.",
        "sort_order": 30,
    },
    {
        "code": "nickname",
        "name": "Přezdívka",
        "description": "Neformální nebo používané označení osoby.",
        "sort_order": 40,
    },
)
INITIAL_NAME_TYPE_CODES = tuple(
    name_type["code"] for name_type in INITIAL_NAME_TYPES
)


def create_initial_name_types(apps, schema_editor) -> None:
    name_type_model = apps.get_model("people", "NameType")

    for name_type in INITIAL_NAME_TYPES:
        name_type_model.objects.update_or_create(
            code=name_type["code"],
            defaults={
                "name": name_type["name"],
                "description": name_type["description"],
                "sort_order": name_type["sort_order"],
                "is_active": True,
                "is_system": True,
            },
        )


def remove_initial_name_types(apps, schema_editor) -> None:
    name_type_model = apps.get_model("people", "NameType")
    name_type_model.objects.filter(
        code__in=INITIAL_NAME_TYPE_CODES
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_name_type_person_name'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_name_types,
            remove_initial_name_types,
        ),
    ]
