# Generated by Django 5.2.16 on 2026-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_initial_name_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(default=False, editable=False),
                ),
                ("forward_label_male", models.CharField(max_length=100)),
                (
                    "forward_label_female",
                    models.CharField(max_length=100),
                ),
                (
                    "forward_label_unknown",
                    models.CharField(max_length=100),
                ),
                ("reverse_label_male", models.CharField(max_length=100)),
                (
                    "reverse_label_female",
                    models.CharField(max_length=100),
                ),
                (
                    "reverse_label_unknown",
                    models.CharField(max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("parent_child", "Rodič a dítě"),
                            ("partner", "Partnerství"),
                            ("sibling", "Sourozenectví"),
                            ("godparent", "Kmotrovství"),
                            ("care", "Péče a poručenství"),
                            ("social", "Sociální vazba"),
                            ("other", "Jiná vazba"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_symmetric", models.BooleanField(default=False)),
                (
                    "supports_date_range",
                    models.BooleanField(default=False),
                ),
                ("is_derivable", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Typ vazby",
                "verbose_name_plural": "Typy vazeb",
                "ordering": ("sort_order", "name", "code"),
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_symmetric", False),
                            models.Q(
                                (
                                    "forward_label_male",
                                    models.F("reverse_label_male"),
                                ),
                                (
                                    "forward_label_female",
                                    models.F("reverse_label_female"),
                                ),
                                (
                                    "forward_label_unknown",
                                    models.F("reverse_label_unknown"),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name=(
                            "people_symmetric_relationship_labels_match"
                        ),
                    )
                ],
            },
        ),
    ]
