# Generated by Django 5.2.16 on 2026-07-20 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_initial_relationship_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Veřejné"),
                            ("authenticated", "Pouze přihlášení"),
                            ("restricted", "Omezené"),
                            ("admin_only", "Pouze správce"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Ověřeno"),
                            ("probable", "Pravděpodobné"),
                            ("uncertain", "Nejisté"),
                            ("disputed", "Sporné"),
                            ("unconfirmed", "Nepotvrzené"),
                        ],
                        default="unconfirmed",
                        max_length=20,
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("archive_reason", models.TextField(blank=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("deletion_reason", models.TextField(blank=True)),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("exact", "Přesné datum"),
                            ("month", "Měsíc a rok"),
                            ("year", "Pouze rok"),
                            ("range", "Rozmezí"),
                            ("unknown", "Neznámé datum"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "date_qualifier",
                    models.CharField(
                        choices=[
                            ("none", "Bez kvalifikátoru"),
                            ("approximate", "Přibližně"),
                            ("before", "Před"),
                            ("after", "Po"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "start_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "end_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "end_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "original_date_text",
                    models.CharField(blank=True, max_length=255),
                ),
                ("date_note", models.TextField(blank=True)),
                (
                    "sort_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "sort_date_end",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_as_a",
                        to="people.person",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships_as_b",
                        to="people.person",
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships",
                        to="people.relationshiptype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vazba",
                "verbose_name_plural": "Vazby",
                "ordering": (
                    "relationship_type__sort_order",
                    "sort_date",
                    "sort_date_end",
                    "person_a_id",
                    "person_b_id",
                    "pk",
                ),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("person_a", models.F("person_b")),
                            _negated=True,
                        ),
                        name="people_relationship_distinct_persons",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("date_precision", "unknown"),
                            ("deleted_at__isnull", True),
                        ),
                        fields=(
                            "person_a",
                            "person_b",
                            "relationship_type",
                        ),
                        name=(
                            "people_unique_active_unknown_relationship"
                        ),
                        violation_error_code="duplicate_relationship",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            models.Q(
                                ("date_precision", "unknown"),
                                _negated=True,
                            ),
                        ),
                        fields=(
                            "person_a",
                            "person_b",
                            "relationship_type",
                            "date_precision",
                            "sort_date",
                            "sort_date_end",
                        ),
                        name="people_unique_active_dated_relationship",
                        violation_error_code="duplicate_relationship",
                    ),
                ],
            },
        ),
    ]
