# Generated by Django 5.2.16 on 2026-07-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={
                'ordering': ('last_name', 'first_name'),
                'permissions': (
                    (
                        'view_archived_person',
                        'Může zobrazit archivované osoby',
                    ),
                    (
                        'view_deleted_person',
                        'Může zobrazit měkce odstraněné osoby',
                    ),
                ),
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
            },
        ),
    ]
