# Generated by Django 5.2.16 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="person",
            name="title_after_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="title_before_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
